---
- name: Ensure remote directory exists
  become: true
  ansible.builtin.file:
    path: "{{ remote_project_dir }}"
    state: directory
    mode: '0755'
  tags: [copy, sync]

- name: Sync project directories to remote nodes
  ansible.posix.synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    delete: false
    recursive: true
    use_ssh_args: true
    rsync_path: sudo rsync
    rsync_opts: "{{ item.rsync_opts | default([]) }}"
  loop:
    - { src: "{{ project_dir }}/certs/", dest: "{{ remote_project_dir }}/certs/" }
    - src: "{{ project_dir }}/config/"
      dest: "{{ remote_project_dir }}/config/"
      rsync_opts: ['--exclude=/pxc/custom.cnf', '--exclude=/pxc/init.cnf']
    - { src: "{{ project_dir }}/docker-compose.yml", dest: "{{ remote_project_dir }}/docker-compose.yml" }
    - { src: "{{ project_dir }}/databases/", dest: "{{ remote_project_dir }}/databases/" }
    - { src: "{{ project_dir }}/Dockerfile", dest: "{{ remote_project_dir }}/Dockerfile"}
  loop_control:
    label: "{{ item.src }}"
  delegate_to: localhost
  tags: [copy, sync]

- name: Sync rendered node configuration to remote nodes
  ansible.posix.synchronize:
    src: "{{ rendered_project_dir }}/"
    dest: "{{ remote_project_dir }}/"
    delete: false
    recursive: true
    use_ssh_args: true
    rsync_path: sudo rsync
  delegate_to: localhost
  tags: [copy, sync]

- name: Ensure PrivacyIDEA can persist its audit keys
  become: true
  ansible.builtin.file:
    path: "{{ remote_project_dir }}/config/privacyidea/keys"
    state: directory
    owner: nobody
    group: nogroup
    mode: '0775'
  tags: [copy, sync]
