---
- hosts: localhost
  gather_facts: false
  roles:
    - role: generate_creds
      tags: [vault, certs, env]
    - role: build_image

- hosts: cluster
  gather_facts: false
  roles:
    - role: deploy
