#!/bin/sh
set -e

mariadb --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
	CREATE DATABASE IF NOT EXISTS \`${PI_DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	CREATE USER IF NOT EXISTS '${PI_DB_USER}'@'%' IDENTIFIED BY '${PI_DB_PASSWORD}';
	GRANT ALL PRIVILEGES ON \`${PI_DB_NAME}\`.* TO '${PI_DB_USER}'@'%';
	FLUSH PRIVILEGES;
EOSQL
